sudo: required
dist: trusty
language: go
install: true

go:
    - 1.9
    - 1.11
    - 1.12
    - 1.13

before_script:
    - sudo apt-get install -y libibverbs-dev

script:
   - cd ${TRAVIS_BUILD_DIR}
   - hack/verify-gofmt.sh
   - ./build
